---
#===========================================
#
# [SugarSS Rules]
#
# @author Koichi Nagaoka
#
# [reference]
# https://stylelint.io/user-guide/rules/
#===========================================
extends: "stylelint-config-sugarss-recommended"
ignoreFiles:
  - "./node_modules/**/*"
